### ISSUE TITLE
[Bug]: proprietary components added with v1.712

### ISSUE THREAD

**Issue by IzzySoft** [ViscousPot/GitSync#216]
### Description

v1.712 arrived at IzzyOnDroid today and had our scanners scream:

* Firebase Data Transport (Utility) **NonFreeNet**
* Play Services Places Placereport (Map) **NonFreeComp,NonFreeNet**
* Google Mobile Services (Development Framework) **NonFreeComp**
* Firebase (Utility) **NonFreeNet,NonFreeComp**
* BillingClient (Payment) **NonFreeComp,NonFreeNet**

That renders this app effectively "no longer FOSS". As your release notes give no clue: maybe some dependency dragged those in? Then `gradle :app:dependencies` might help you find the culprit. Should it OTOH have been intended: maybe you'd consider a FOSS build flavor? For now, at IzzyOnDroid we need to raise the proper anti-features until this is solved:

```yaml
AntiFeatures:
  NonFreeComp:
    en-US: The app contains Play Services Places Placereport, GMS, Firebase and BillingClient libraries.
    de: Die App enthält Play Services Places Placereport, GMS, Firebase und BillingClient Bibliotheken.
  NonFreeNet:
    en-US: The app uses connections to Google servers (see NonFreeComp).
    de: Die App verwendet Verbindungen zu Google Servern (siehe NonFreeComp).
```

### Minimal Reproduction

n/a
